### ISSUE TITLE
字体下载成功但是无法切换，界面闪一下就回退到默认字体。

### ISSUE THREAD

**Issue by duduhappy2003** [yujixia/kindle_fonts#1]
iOS版本16.3.1
kindle app版本6.73
代理软件quanx
代理软件显示302重定向成功的。字体下载成功，但是在字体选择界面选择字体，阅读界面闪一下，然后恢复到“系统字体”。

**Comment by AmiimiiA** [comment]
> iOS版本16.3.1
> 
> kindle app版本6.73
> 
> 代理软件quanx
> 
> 代理软件显示302重定向成功的。字体下载成功，但是在字体选择界面选择字体，阅读界面闪一下，然后恢复到“系统字体”。

iOS，亚马逊购买的电子书可以，个人文档不行。

**Comment by duduhappy2003** [comment]
> > iOS版本16.3.1
> > kindle app版本6.73
> > 代理软件quanx
> > 代理软件显示302重定向成功的。字体下载成功，但是在字体选择界面选择字体，阅读界面闪一下，然后恢复到“系统字体”。
> 
> iOS，亚马逊购买的电子书可以，个人文档不行。

难怪了，我说怎么修改不了，感谢大佬解惑~
